apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "pkivaultservice.name" . }}-dpl"
  labels:
{{ include "pkivaultservice.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:
{{ include "pkivaultservice.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pkivaultservice.labels" . | indent 8 }}
      annotations:
        kubectl.kubernetes.io/default-logs-container: {{ include "pkivaultservice.name" . }}
    spec:
      {{- with .Values.podSecurityContext }}
      podSecurityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "pkivaultservice.name" . }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.port }}
        envFrom:
        - configMapRef:
            name: {{ include "pkivaultservice.name" . }}-cm
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
        # lifecycle:
        #   preStop:
        #     exec:
        #       command: {{ toYaml .Values.lifecycle.preStop.exec.command | nindent 14 }}