apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "pkiVaultService.name" . }}-dpl"
  labels:
{{ include "pkiVaultService.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:
{{ include "pkiVaultService.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pkiVaultService.labels" . | indent 8 }}
      annotations:
        kubectl.kubernetes.io/default-logs-container: {{ include "pkiVaultService.name" . }}
    spec:
      {{- with .Values.podSecurityContext }}
      podSecurityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "pkiVaultService.name" . }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.port }}
        envFrom:
        - configMapRef:
            name: {{ include "pkiVaultService.name" . }}-cm
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
        lifecycle:
          {{ toYaml .Values.lifecycle | nindent 10 }}