// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: pkivault.proto

package pkiVault

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PkiVault_GetUsers_FullMethodName         = "/pkiVault.pkiVault/GetUsers"
	PkiVault_GetUserProfile_FullMethodName   = "/pkiVault.pkiVault/GetUserProfile"
	PkiVault_GetUserInterests_FullMethodName = "/pkiVault.pkiVault/GetUserInterests"
	PkiVault_CreateUser_FullMethodName       = "/pkiVault.pkiVault/CreateUser"
	PkiVault_UpdateUser_FullMethodName       = "/pkiVault.pkiVault/UpdateUser"
	PkiVault_DeleteUser_FullMethodName       = "/pkiVault.pkiVault/DeleteUser"
)

// PkiVaultClient is the client API for PkiVault service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PkiVaultClient interface {
	GetUsers(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserList, error)
	GetUserProfile(ctx context.Context, in *UserInList, opts ...grpc.CallOption) (*UserInList, error)
	GetUserInterests(ctx context.Context, in *UserInList, opts ...grpc.CallOption) (*UserInterests, error)
	CreateUser(ctx context.Context, in *UserInList, opts ...grpc.CallOption) (*Response, error)
	UpdateUser(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteUser(ctx context.Context, in *UserInList, opts ...grpc.CallOption) (*Response, error)
}

type pkiVaultClient struct {
	cc grpc.ClientConnInterface
}

func NewPkiVaultClient(cc grpc.ClientConnInterface) PkiVaultClient {
	return &pkiVaultClient{cc}
}

func (c *pkiVaultClient) GetUsers(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserList)
	err := c.cc.Invoke(ctx, PkiVault_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pkiVaultClient) GetUserProfile(ctx context.Context, in *UserInList, opts ...grpc.CallOption) (*UserInList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInList)
	err := c.cc.Invoke(ctx, PkiVault_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pkiVaultClient) GetUserInterests(ctx context.Context, in *UserInList, opts ...grpc.CallOption) (*UserInterests, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInterests)
	err := c.cc.Invoke(ctx, PkiVault_GetUserInterests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pkiVaultClient) CreateUser(ctx context.Context, in *UserInList, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PkiVault_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pkiVaultClient) UpdateUser(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PkiVault_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pkiVaultClient) DeleteUser(ctx context.Context, in *UserInList, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PkiVault_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PkiVaultServer is the server API for PkiVault service.
// All implementations must embed UnimplementedPkiVaultServer
// for forward compatibility.
type PkiVaultServer interface {
	GetUsers(context.Context, *UserRequest) (*UserList, error)
	GetUserProfile(context.Context, *UserInList) (*UserInList, error)
	GetUserInterests(context.Context, *UserInList) (*UserInterests, error)
	CreateUser(context.Context, *UserInList) (*Response, error)
	UpdateUser(context.Context, *UserUpdateRequest) (*Response, error)
	DeleteUser(context.Context, *UserInList) (*Response, error)
	mustEmbedUnimplementedPkiVaultServer()
}

// UnimplementedPkiVaultServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPkiVaultServer struct{}

func (UnimplementedPkiVaultServer) GetUsers(context.Context, *UserRequest) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedPkiVaultServer) GetUserProfile(context.Context, *UserInList) (*UserInList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedPkiVaultServer) GetUserInterests(context.Context, *UserInList) (*UserInterests, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInterests not implemented")
}
func (UnimplementedPkiVaultServer) CreateUser(context.Context, *UserInList) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedPkiVaultServer) UpdateUser(context.Context, *UserUpdateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedPkiVaultServer) DeleteUser(context.Context, *UserInList) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedPkiVaultServer) mustEmbedUnimplementedPkiVaultServer() {}
func (UnimplementedPkiVaultServer) testEmbeddedByValue()                  {}

// UnsafePkiVaultServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PkiVaultServer will
// result in compilation errors.
type UnsafePkiVaultServer interface {
	mustEmbedUnimplementedPkiVaultServer()
}

func RegisterPkiVaultServer(s grpc.ServiceRegistrar, srv PkiVaultServer) {
	// If the following call pancis, it indicates UnimplementedPkiVaultServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PkiVault_ServiceDesc, srv)
}

func _PkiVault_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PkiVaultServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PkiVault_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PkiVaultServer).GetUsers(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PkiVault_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PkiVaultServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PkiVault_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PkiVaultServer).GetUserProfile(ctx, req.(*UserInList))
	}
	return interceptor(ctx, in, info, handler)
}

func _PkiVault_GetUserInterests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PkiVaultServer).GetUserInterests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PkiVault_GetUserInterests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PkiVaultServer).GetUserInterests(ctx, req.(*UserInList))
	}
	return interceptor(ctx, in, info, handler)
}

func _PkiVault_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PkiVaultServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PkiVault_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PkiVaultServer).CreateUser(ctx, req.(*UserInList))
	}
	return interceptor(ctx, in, info, handler)
}

func _PkiVault_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PkiVaultServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PkiVault_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PkiVaultServer).UpdateUser(ctx, req.(*UserUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PkiVault_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PkiVaultServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PkiVault_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PkiVaultServer).DeleteUser(ctx, req.(*UserInList))
	}
	return interceptor(ctx, in, info, handler)
}

// PkiVault_ServiceDesc is the grpc.ServiceDesc for PkiVault service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PkiVault_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkiVault.pkiVault",
	HandlerType: (*PkiVaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _PkiVault_GetUsers_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _PkiVault_GetUserProfile_Handler,
		},
		{
			MethodName: "GetUserInterests",
			Handler:    _PkiVault_GetUserInterests_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _PkiVault_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _PkiVault_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _PkiVault_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkivault.proto",
}
