# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build and publish artifact

on:
  push:
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Extract tag from the reference
      run: |
        ZOLARA_GIT_TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        echo "Tag name is $ZOLARA_GIT_TAG"
        echo "ZOLARA_GIT_TAG=$ZOLARA_GIT_TAG" >> $GITHUB_ENV
    
    - name: Build with tag
      run: go build -a -installsuffix cgo -o pki-vault-service-${ZOLARA_GIT_TAG} .

    - name: Upload artifact with tag
      uses: actions/upload-artifact@v4
      with:
        name: pki-vault-service-${{ env.ZOLARA_GIT_TAG }}
        path: ${{ github.workspace }}/pki-vault-service-${{ env.ZOLARA_GIT_TAG }}

    - name: Configure Docker for insecure registry
      run: |
        echo '{ "insecure-registries" : ["nexuszolara.me"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ env.HARBOR_PATH }}
        username: ${{ env.HARBOR_USERNAME  }}
        password: ${{ env.HARBOR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.HARBOR_PATH }}/pki-vault-service:${{ env.ZOLARA_GIT_TAG }} .
        docker push ${{ env.HARBOR_PATH }}/pki-vault-service:${{ env.ZOLARA_GIT_TAG }}

    - name: Push the helm chart to Harbor
      run: |
        helm package helm/pki-vault-service
        helm push pki-vault-service-${{ env.ZOLARA_GIT_TAG }} ${{ env.HARBOR_PATH }}/pki-vault-service-helm-${{ env.ZOLARA_GIT_TAG }}.tgz